language: swift
osx_image: xcode11.3

script:
- xctool clean build -workspace DHCountryPicker.xcworkspace -scheme Example -sdk iphonesimulator | xcpretty
- xcodebuild test -workspace DHCountryPicker.xcworkspace -scheme Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=12.4' | xcpretty