language: swift
osx_image: xcode11.3

script:
- xcodebuild -enableCodeCoverage=YES clean test -workspace DHCountryPicker.xcworkspace -scheme Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=12.4' | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)